In [79]:
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
a1=np.array([10,20,30,40,50])

In [3]:
print(a1)

[10 20 30 40 50]


In [4]:
a1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [5]:
b1=a1

In [6]:
b1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [7]:
b2=a1[:3]

# 1. Metadata of numpy array

In [8]:
b2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# 2. Returns data type of array

In [9]:
b2.dtype

dtype('int64')

# 3. Gives size of array

In [10]:
b1.size

5

# 4. Give size of each items in bytes

In [11]:
b1.itemsize

8

# 5. Give size of whole array in bytes

In [12]:
b1.nbytes

40

# 6. Dimension of array

In [13]:
b1.ndim

1

# 7. Returns number of values in respective dimension

In [14]:
b1.shape

(5,)

In [15]:
a1=np.array([[20,30,40],[40,50,30]])

In [16]:
a1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [17]:
a1.itemsize

8

In [18]:
a1.size

6

In [19]:
a1.nbytes

48

In [20]:
a1.shape


(2, 3)

In [21]:
a1.ndim

2

In [22]:
a1.dtype

dtype('int64')

In [23]:
a5=np.arange(1,10,2)

##### 

In [24]:
a5

array([1, 3, 5, 7, 9])

In [25]:
a6=np.random.random(5)
a6

array([0.38969641, 0.91728805, 0.29436015, 0.30515357, 0.92852321])

In [26]:
a7=np.random.randint(5,50,5)
a7

array([13, 47,  8, 39, 26])

In [27]:
a8=np.array([[2,3],[3,5],[8,9]])


In [28]:
a8.reshape(2,3)

array([[2, 3, 3],
       [5, 8, 9]])

In [29]:
a8

array([[2, 3],
       [3, 5],
       [8, 9]])

In [30]:
a9=np.zeros(5,dtype='int8')
a9

array([0, 0, 0, 0, 0], dtype=int8)

In [31]:
a10=np.ones(6,dtype='int8')
a10

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [32]:
print(a8.mean())

5.0


In [33]:
print(a8+a8.reshape(2,3))

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [34]:
    salaries = np.array([10.50, 14.50, 12, 20, 18])

    # find the salaries > 15
    print(f"salaries > 15 = {salaries > 15}")
    print(f"salaries[[False, False, False,  True,  True]] = {salaries[[False, False, False,  True,  True]]}")

salaries > 15 = [False False False  True  True]
salaries[[False, False, False,  True,  True]] = [20. 18.]


In [35]:

    car_prices = [20, 35, 40, 56, 70, 85, 10, 22, 18]

    # get the affordability status of every car
    # if car's price is > 30 its not affordable
    # status should be "Affordable" or "Not Affordable"
    print(["Affordable" if price < 30 else "Not Affordable" for price in car_prices])
    print([("Affordable", price) if price < 30 else ("Not Affordable", price) for price in car_prices])
    

['Affordable', 'Not Affordable', 'Not Affordable', 'Not Affordable', 'Not Affordable', 'Not Affordable', 'Affordable', 'Affordable', 'Affordable']
[('Affordable', 20), ('Not Affordable', 35), ('Not Affordable', 40), ('Not Affordable', 56), ('Not Affordable', 70), ('Not Affordable', 85), ('Affordable', 10), ('Affordable', 22), ('Affordable', 18)]


In [36]:
# A dictionary representing employees
employees = {
    101: {"name": "Alice", "role": "Dev", "salary": 75000},
    102: {"name": "Bob", "role": "Design", "salary": 65000},
    103: {"name": "Charlie", "role": "PM", "salary": 80000}
}

In [37]:
for emp_id, info in employees.items():
    print(f"ID: {emp_id}")
    # 'info' is the inner dictionary
    # print(f"Name: {info['name']}, Role: {info['role']}")
    # print("-" * 10)

ID: 101
ID: 102
ID: 103


In [38]:
employees.items()


dict_items([(101, {'name': 'Alice', 'role': 'Dev', 'salary': 75000}), (102, {'name': 'Bob', 'role': 'Design', 'salary': 65000}), (103, {'name': 'Charlie', 'role': 'PM', 'salary': 80000})])

In [39]:
d1=[ [i,j]  for ele,info in employees.items() for i,j in info.items()]

In [40]:
d1

[['name', 'Alice'],
 ['role', 'Dev'],
 ['salary', 75000],
 ['name', 'Bob'],
 ['role', 'Design'],
 ['salary', 65000],
 ['name', 'Charlie'],
 ['role', 'PM'],
 ['salary', 80000]]

In [41]:
av=np.array([101,102,103,104,105])

In [42]:
av1=np.arange(3,13,3)
av1

array([ 3,  6,  9, 12])

In [43]:
av2=np.random.random(10)
av2

array([0.11385565, 0.42631251, 0.02692334, 0.633617  , 0.23377788,
       0.66930791, 0.51648366, 0.74656751, 0.74114188, 0.42782055])

In [44]:
av3=np.random.randint(10,100,5)
av3

array([11, 68, 74, 47, 52])

In [45]:
av4=np.array([[10,20,30],[30,40,50]])

In [46]:
av4.reshape(3,2)

array([[10, 20],
       [30, 30],
       [40, 50]])

In [47]:
    series1 = pd.Series([10, 20, 30, 40, 50])
    print(series1)
    print("-" * 80)

    # create a series using tuple
    series2 = pd.Series((10, 20, 30, 40, 50))
    print(series2)
    print("-" * 80)

    # create a series using set
    # this does not work as Set is unordered collection of unique values
    # series3 = pd.Series({10, 20, 30, 40, 50})
    # print(series3)

    # create a series using dictionary
    series4 = pd.Series({"name": "person1", "address": "pune", "age": 30})
    print(series4)
    print("-" * 80)

    # create a series using numpy array
    array = np.array([10, 20, 30, 40, 50])
    series5 = pd.Series(array)
    print(series5)

0    10
1    20
2    30
3    40
4    50
dtype: int64
--------------------------------------------------------------------------------
0    10
1    20
2    30
3    40
4    50
dtype: int64
--------------------------------------------------------------------------------
name       person1
address       pune
age             30
dtype: object
--------------------------------------------------------------------------------
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [48]:
import numpy as np

a = np.array([[10, 20, 30, 40, 50],[40,50,30,20,70]])

# Case 1: Slicing (Shared Memory)
b_view = a[1:3]
print(np.shares_memory(a, b_view))  # Returns: True

# Case 2: Fancy Indexing (Different Memory)
b_copy = a[1:3]
print(np.shares_memory(a, b_copy))  # Returns: False

True
True


In [49]:
a.shape

(2, 5)

In [50]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [51]:
b_view.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [52]:
c=np.zeros(5,dtype='int8')
c

array([0, 0, 0, 0, 0], dtype=int8)

In [53]:
c.size

5

In [54]:
c.itemsize

1

In [55]:
c.nbytes

5

In [56]:
z=np.random.randint(1,10,5)

In [57]:
z

array([2, 7, 3, 2, 8])

In [58]:
z1=np.arange(5,15,2)

In [59]:
z1

array([ 5,  7,  9, 11, 13])

In [60]:
dict1={"first":{"name":"Viveksingh","Roll_no":30,"place":"Nagpur"},"second":{"name":"Ramsingh","Roll_no":90,"place":"Nagpur"}}
g1=pd.DataFrame(dict1)

In [61]:
dict2=[{"name":"Viveksingh","Roll_no":30,"place":"Nagpur"},{"name":"Ramsingh","Roll_no":90,"place":"Nagpur"}]
g2=pd.DataFrame(dict2)

In [62]:
g2

,name,Roll_no,place
0,Viveksingh,30,Nagpur
1,Ramsingh,90,Nagpur


In [63]:
person = {"name": "person1", "age": 30, "address": "pune"}
s3 = pd.Series(person)

In [64]:
s3

name       person1
age             30
address       pune
dtype: object

In [65]:
def timmer(orginal_fun):
    def wrapper(*args,**kwargs):
        print("In wrapper func")
        return orginal_fun(*args,**kwargs)
    return wrapper


@timmer
def Display():
    print("Inside display")

Display()

In wrapper func
Inside display


In [66]:
def multipler_factory(n):
    def multipler(m):
        result=m*n
        return result
    return multipler
double=multipler_factory(2)
print(double(10))



20


In [67]:
bios_data=pd.read_csv("/Users/A200287292/Downloads/bios.csv")

In [68]:
display(bios_data)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18


In [69]:
bios_data.sample(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
26737,26932,Dariusz Gęsior,1969-10-09,Chorzów,Śląskie,POL,Poland,188.0,78.0,NaN
41046,41361,Deborah Srour,1962-03-19,São Paulo,São Paulo,BRA,Brazil,164.0,64.0,NaN
407,408,Jorge Murillo,1939-11-15,San José,San José,CRC,Costa Rica,180.0,81.0,NaN
116540,117934,Xi Aihua,1982-01-27,Shouguang,Shandong,CHN,People's Republic of China,182.0,80.0,NaN
34340,34605,Udo Birnbaum,1937-02-08,Zell an der Ybbs,Niederösterreich,AUT,Austria,172.0,65.0,NaN
56459,56861,Cemal Erçman,1900-01-01,Thessaloniki,Thessalia,GRE,Türkiye,NaN,NaN,1978-01-01
72741,73294,Nezha Bidouane,1969-09-18,Rabat,Rabat-Salé-Kénitra,MAR,Morocco,174.0,65.0,NaN
18298,18420,Ibrahim Mahmoud Tawfik,1965-09-05,NaN,NaN,NaN,Egypt,NaN,NaN,NaN
129823,132469,Patrick Tiernan,1994-09-11,Toowoomba,Queensland,AUS,Australia,183.0,83.0,NaN
29428,29648,Poul Jessen,1926-02-17,København (Copenhagen),Hovedstaden,DEN,Denmark,NaN,NaN,2015-06-16


In [70]:
bios_data.loc[:,"name"]

0         Jean-François Blanchy
1                Arnaud Boetsch
2                  Jean Borotra
3               Jacques Brugnon
4                  Albert Canet
                  ...          
145495        Polina Luchnikova
145496      Valeriya Merkusheva
145497          Yuliya Smirnova
145498           André Foussard
145499            Bill Phillips
Name: name, Length: 145500, dtype: object

In [71]:
bios_data.iloc[:,[1,2]]

,name,born_date
0,Jean-François Blanchy,1886-12-12
1,Arnaud Boetsch,1969-04-01
2,Jean Borotra,1898-08-13
3,Jacques Brugnon,1895-05-11
4,Albert Canet,1878-04-17
...,...,...
145495,Polina Luchnikova,2002-01-30
145496,Valeriya Merkusheva,1999-09-20
145497,Yuliya Smirnova,1998-05-08
145498,André Foussard,1899-05-19


In [72]:
# bios_data.index=bios_data["athlete_id"]

In [73]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25


In [74]:
bios_data.sort_values(["athlete_id"],axis=0,ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN


In [75]:
bios_data.loc[bios_data["born_city"].isin( ["Dulwich Hill","Niort","Serov"]),["name","athlete_id"]]

,name,athlete_id
8518,Kostya Tszyu,8565
11578,Jean-Jacques Boisson,11639
36722,Vincent Lepvraud,37016
62981,Patrick Rieupeyrout,63451
67989,André Sicard,68504
95603,Nicolas Petorin,96374
108351,Nataliya Tobias,109502
118818,Pavel Trenikhin,120574
131158,Emmanuel Lebesson,133922
139426,Nicolas Tournat,142899


In [76]:
bios_data["first_name"]=bios_data["name"].str.split(" ").str[0]

In [77]:
display(bios_data)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André


In [83]:
bios_data["born_year"]=bios_data["born_date"].dt.year

In [81]:
bios_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   athlete_id    145500 non-null  int64  
 1   name          145500 non-null  object 
 2   born_date     143693 non-null  object 
 3   born_city     110908 non-null  object 
 4   born_region   110908 non-null  object 
 5   born_country  110908 non-null  object 
 6   NOC           145499 non-null  object 
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object 
 10  first_name    145500 non-null  object 
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB


In [82]:
bios_data["born_date"]=pd.to_datetime(bios_data["born_date"],errors='coerce')

In [85]:
bios_data[["name","born_date","born_year"]]

,name,born_date,born_year
0,Jean-François Blanchy,1886-12-12,1886.0
1,Arnaud Boetsch,1969-04-01,1969.0
2,Jean Borotra,1898-08-13,1898.0
3,Jacques Brugnon,1895-05-11,1895.0
4,Albert Canet,1878-04-17,1878.0
...,...,...,...
145495,Polina Luchnikova,2002-01-30,2002.0
145496,Valeriya Merkusheva,1999-09-20,1999.0
145497,Yuliya Smirnova,1998-05-08,1998.0
145498,André Foussard,1899-05-19,1899.0


In [87]:
bios_data["heigh_category"]=bios_data["height_cm"].apply(lambda x: "short" if x<165 else( "average" if x<185 else "tall"))

# Apply

# The apply() function in pandas allows you to apply a custom function to each element, row, or column of a DataFrame or Series.

In [88]:
dict1=[{"name":"Viveksingh","salary":150000},{"name":"Annu","salary":"100000"}]

In [92]:
dict1=sorted(dict1,key= lambda x:int(x["salary"]),reverse=False)

In [93]:
dict1

[{'name': 'Annu', 'salary': '100000'},
 {'name': 'Viveksingh', 'salary': 150000}]

# Interpolate
# The interpolate() function in pandas fills in missing values (NaN) by estimating them based on surrounding data points.

In [94]:
bios_data.isna()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,heigh_category
0,False,False,False,False,False,False,False,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,False,False,False,False,False,False,False,False,False,True,False,False,False
145496,False,False,False,False,False,False,False,False,False,True,False,False,False
145497,False,False,False,False,False,False,False,False,False,True,False,False,False
145498,False,False,False,False,False,False,False,False,True,False,False,False,False


In [95]:
bios_data.loc[0:5,:]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,heigh_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Nicolas,1970.0,average


In [98]:
bios_data["weight_kg"].interpolate(inplace=True)

/var/folders/kz/zvcx4y390ss_lfr1f3xhx74c0000gq/T/ipykernel_49924/3612091417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bios_data["weight_kg"].interpolate(inplace=True)


In [99]:
bios_data.loc[0:5,:]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,heigh_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,67.0,1930-07-25,Albert,1878.0,tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Nicolas,1970.0,average


In [102]:
bios_data["born_country"].value_counts()

born_country
USA        9641
GER        6891
GBR        5792
FRA        5143
ITA        4709
           ... 
GIB           1
NFI           1
Munich        1
Altmark       1
Aarhus        1
Name: count, Length: 236, dtype: int64

In [104]:
bios_data["shifted_hieght"]=bios_data["height_cm"].shift(2)

In [105]:
bios_data

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,heigh_category,shifted_hieght
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,tall,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,average,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,average,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,average,183.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,67.0,1930-07-25,Albert,1878.0,tall,183.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002.0,average,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999.0,average,183.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998.0,short,167.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,55.0,1986-03-18,André,1899.0,average,168.0


In [107]:
bios_data.sort_values(["athlete_id"]).sample(10).rank()[["athlete_id","name","born_region"]]

,athlete_id,name,born_region
91444,9.0,5.0,2.0
44173,6.0,1.0,NaN
88427,8.0,6.0,7.0
1755,1.0,4.0,4.0
4757,2.0,3.0,3.0
133374,10.0,7.0,5.0
15856,3.0,8.0,NaN
32926,5.0,10.0,6.0
45625,7.0,2.0,1.0
28057,4.0,9.0,NaN


# A pivot table reorganizes and summarizes data by grouping and aggregating values. It transforms rows into columns (or vice versa) to make data easier to analyze.

In [108]:
bios_data.pivot_table(values=

SyntaxError: incomplete input (3118150369.py, line 1)

# Aggreagation

In [117]:
class vehicle:
    def __init__(self):
        print("Inside vehicle")
class engine:
    def __init__(self,veh):
        print("Inside engine")
        self.veh=veh
    def engine_spec(self):
        print("v8 engine")
v1=vehicle()
e1=engine(v1)


Inside vehicle
Inside engine


# Composition

In [121]:
class vehicle:
    def __init__(self,num):
        self.status="ready"
        print(f"Inside vehicle{num}")
class engine:
    def __init__(self):
        self.veh1=vehicle(1)
        self.veh2=vehicle(2)
    def engine_spec(self,num):
        veh_obj=getattr(self,f"veh{num}")
        print(f"v8 engine status: {veh_obj.status}")
        
e1=engine()
e1.engine_spec(1)

Inside vehicle1
Inside vehicle2
v8 engine status: ready


In [2]:
from itertools import groupby

S=input()
output="".join([f"{key}{len(list(group))}" for key,group in groupby(S)])
print(output)
    

 aaaccc


a3c3


In [5]:



s=input()
output="".join([s[k]*int(s[k+1]) for k in range(0,len(s),2)])
print(output)

 fffddd


ValueError: invalid literal for int() with base 10: 'f'

In [8]:
results = {k: g for k, g in groupby("AAABBB")}
results

{'A': <itertools._grouper at 0x107b01e10>,
 'B': <itertools._grouper at 0x107b01780>}

In [16]:
from itertools import groupby

s="aaaabbbccaa"

result="".join(f"{x}{len(list(y))}" for x,y in groupby(s))

result

'a4b3c2a2'

In [27]:
# def log_reader(filename):
#     with open(filename,"r") as f:
#         for line in f:
#             if "error" in line:
#                 yield line.strip()
# errors = log_reader("/Users/A200287292/Downloads/server.log")
# for error in errors:
#     print(f"Found an issue: {error}")

In [28]:
errors=(lines.strip()  for lines in open("/Users/A200287292/Downloads/server.log","r") if "error" in lines)

In [26]:
for error in errors:
    print(f"Found an issue: {error}")

Found an issue: "error : error1"
Found an issue: "error : error2"


In [7]:
def fib(n):
    if n<1:
        return 1
    return fib(n-1)+fib(n-2)

print(fib(4))

8


In [8]:
def factorial(n):
    if n<1:
        return 1
    return factorial(n-1)*n

print(factorial(5))

3628800


In [19]:
def recurrsion(arr,key,l,r):
    if l>r:
        return -1
    else:
        mid=(l+r)//2
        if arr[mid]>key:
            recurrsion(arr,key,0,mid-1)
        elif arr[mid]<key:
            recurrsion(arr,key,mid+1,r)
        elif arr[mid]==key:
            print(f"{key} found")
            return
    
        

In [20]:
l1=[1,2,3,5,7,8,10,22,44,55]
recurrsion(l1,10,0,len(l1))

10 found


In [8]:
import itertools
a = [2, 4, 6, 7, 8, 10, 11, 12, 13]

# Grouping consecutive even and odd numbers
g_data = itertools.groupby(a, key=lambda x: 'Even' if x % 2 == 0 else 'Odd')
print(g_data)

In [9]:
for key, group in g_data:
    print(f"Group: {key} -> {list(group)}")

Group: Even -> [2, 4, 6]
Group: Odd -> [7]
Group: Even -> [8, 10]
Group: Odd -> [11]
Group: Even -> [12]
Group: Odd -> [13]


In [21]:
string1="aaaabbabababbbababaccc"
output="".join(f"{x}{list(y)}" for x,y in itertools.groupby(string1))

In [22]:
output

"a['a', 'a', 'a', 'a']b['b', 'b']a['a']b['b']a['a']b['b']a['a']b['b', 'b', 'b']a['a']b['b']a['a']b['b']a['a']c['c', 'c', 'c']"